package com.github.weichun97.strategydemo.v5;

import com.github.weichun97.strategydemo.PayTypeVar;
import org.springframework.stereotype.Component;

/**
 * @author chun
 * @date 2021/6/24 10:43
 */
@Component
public class WechatPay implements BasePay {

    @Override
    public int getPayType() {
        return PayTypeVar.WECHAT;
    }

    @Override
    public String getSign() {
        // 此处省略100行.......
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        System.out.println("微信支付签名");
        return "微信支付签名";
    }

    @Override
    public String pay(String sign) {
        // 此处省略100行.......
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        System.out.println("微信支付");
        return "微信支付返回的结果";
    }

    @Override
    public void callback(String res) {
        // 此处省略100行.......
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        System.out.println("微信回调");
    }
}
