package com.github.weichun97.strategydemo.v2;

/**
 * @author chun
 * @date 2021/6/24 10:43
 */
public class WechatPay implements BasePay{
    @Override
    public String getSign() {
        // 此处省略100行.......
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        System.out.println("微信支付签名");
        return "微信支付签名";
    }

    @Override
    public String pay(String sign) {
        // 此处省略100行.......
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        System.out.println("微信支付");
        return "微信支付返回的结果";
    }

    @Override
    public void callback(String res) {
        // 此处省略100行.......
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        //..............,....
        System.out.println("微信回调");
    }
}
